name: Mirror

on: push

jobs:
  mirror:
    # This action should not run in any mirrors (used as workaround for Cloudflare Pages not supporting monorepos)
    if: ${{ !contains(github.repository, 'mirror') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror Repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:fundamend/template-app-mirror.git
          ssh_private_key: ${{ secrets.TEMPLATE_APP_MIRROW_DEPLOY_KEY }}
