name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: fundamend/action-monorepo-package-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Publish Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: publish --env production
      - name: Sentry Release Upload
        uses: fundamend/action-sentry-release-upload@main
        with:
          environment: 'production'
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-organization: 'decouplr'
          sentry-project: 'template-app'
          sourcemaps-path: 'build'
