name: Release Dev

on:
 push:
  branches:
    - 'dev'

jobs:
  release-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Sentry Release Upload
        uses: fundamend/action-sentry-release-upload@main
        with:
          environment: 'preview'
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN}}
          sentry-organization: 'decouplr'
          sentry-project: 'template-app'
          sourcemaps-path: 'build'
