name: Release Dev

on:
  push:
    branches:
      - 'dev'

jobs:
  sentry-release-upload:
    name: Sentry Release Upload (${{ matrix.arrays.name }})
    strategy:
      matrix:
        arrays:
          [
            {
              name: 'page-app',
              working-directory: 'packages/drivers/page-app',
              build-command: 'npm run prod',
              public-sentry-dsn-key: 'PUBLIC_SENTRY_DSN_PAGE_APP'
            },
            {
              name: 'page-www',
              working-directory: 'packages/drivers/page-www',
              build-command: 'npm run prod',
              public-sentry-dsn-key: 'PUBLIC_SENTRY_DSN_PAGE_WWW'
            },
            {
              name: 'worker-test',
              working-directory: 'packages/drivers/worker-test',
              build-command: 'npm run prod:preview',
              public-sentry-dsn-key: 'PUBLIC_SENTRY_DSN_WORKER_TEST'
            },
            {
              name: 'worker-stripe',
              working-directory: 'packages/drivers/worker-stripe',
              build-command: 'npm run prod:preview',
              public-sentry-dsn-key: 'PUBLIC_SENTRY_DSN_WORKER_STRIPE'
            }
          ]
    runs-on: ubuntu-latest
    environment: preview
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      PUBLIC_CLERK_FRONTEND_API: ${{ secrets.PUBLIC_CLERK_FRONTEND_API }}
      PUBLIC_CLERK_JWT_VERIFICATION_KEY: ${{ secrets.PUBLIC_CLERK_JWT_VERIFICATION_KEY }}
      PUBLIC_ENVIRONMENT: ${{ secrets.PUBLIC_ENVIRONMENT }}
      PUBLIC_SENTRY_DSN: ${{ secrets[matrix.arrays.public-sentry-dsn-key] }}
    steps:
      - name: Sentry Release Upload
        uses: fundamend/action-sentry-release-upload@main
        with:
          environment: 'preview'
          sentry-auth-token: ${{ secrets.PRIVATE_SENTRY_AUTH_TOKEN}}
          sentry-organization: 'decouplr'
          sentry-project: ${{ matrix.arrays.name }}
          working-directory: ${{ matrix.arrays.working-directory }}
          build-command: ${{ matrix.arrays.build-command }}

  publish-workers:
    name: Publish Workers (${{ matrix.arrays.name }})
    strategy:
      matrix:
        arrays:
          [
            {
              name: 'worker-test',
              working-directory: 'packages/drivers/worker-test',
              public-sentry-dsn-key: 'PUBLIC_SENTRY_DSN_WORKER_TEST'
            },
            {
              name: 'worker-stripe',
              working-directory: 'packages/drivers/worker-stripe',
              public-sentry-dsn-key: 'PUBLIC_SENTRY_DSN_WORKER_STRIPE'
            }
          ]
    runs-on: ubuntu-latest
    environment: preview
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      PUBLIC_CLERK_FRONTEND_API: ${{ secrets.PUBLIC_CLERK_FRONTEND_API }}
      PUBLIC_CLERK_JWT_VERIFICATION_KEY: ${{ secrets.PUBLIC_CLERK_JWT_VERIFICATION_KEY }}
      PUBLIC_ENVIRONMENT: ${{ secrets.PUBLIC_ENVIRONMENT }}
      PUBLIC_SENTRY_DSN: ${{ secrets[matrix.arrays.public-sentry-dsn-key] }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn
      - name: Publish Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.PRIVATE_CLOUDFLARE_API_TOKEN }}
          workingDirectory: ${{ matrix.arrays.working-directory }}
          command: publish --env preview

  publish-pages:
    name: Publish Pages (${{ matrix.arrays.name }})
    strategy:
      matrix:
        arrays:
          [
            {
              name: 'page-www',
              working-directory: 'packages/drivers/page-www',
              public-sentry-dsn-key: 'PUBLIC_SENTRY_DSN_PAGE_WWW'
            },
            {
              name: 'page-app',
              working-directory: 'packages/drivers/page-app',
              public-sentry-dsn-key: 'PUBLIC_SENTRY_DSN_PAGE_APP'
            }
          ]
    runs-on: ubuntu-latest
    environment: preview
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      PUBLIC_CLERK_FRONTEND_API: ${{ secrets.PUBLIC_CLERK_FRONTEND_API }}
      PUBLIC_CLERK_JWT_VERIFICATION_KEY: ${{ secrets.PUBLIC_CLERK_JWT_VERIFICATION_KEY }}
      PUBLIC_ENVIRONMENT: ${{ secrets.PUBLIC_ENVIRONMENT }}
      PUBLIC_SENTRY_DSN: ${{ secrets[matrix.arrays.public-sentry-dsn-key] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Build page
        shell: bash
        working-directory: ${{ matrix.arrays.working-directory }}
        run: yarn prod

      - name: Publish page
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.PRIVATE_CLOUDFLARE_API_TOKEN }}
          workingDirectory: ${{ matrix.arrays.working-directory }}
          command: pages publish build --branch dev --commit-dirty true --project-name ${{ matrix.arrays.name }}
